CLUSTAL multiple sequence alignment by MUSCLE (3.8)


sp|P22770|ACHA7_CHICK      MGLRALMLWLLAAAGLVRESLQGEFQRKLYKELLKNYNPLERPVANDSQPLTVYFTLSLM
sp|Q05941|ACHA7_RAT        MCGGRGGIWLALAAALLHVSLQGEFQRRLYKELVKNYNPLERPVANDSQPLTVYFSLSLL
sp|P49582|ACHA7_MOUSE      MCGRRGGIWLALAAALLHVSLQGEFQRRLYKELVKNYNPLERPVANDSQPLTVYFSLSLL
sp|P54131|ACHA7_BOVIN      ---MRGSLCLALAASILHVSLQGEFQRKLYKDLVKNYNPLERPVANDSLPLTVYFSLSLL
sp|Q866A2|ACHA7_MACMU      MRCSQGGVWLALAASLLHVSLQGEFQRKLYKELVKNYNPLERPVANDSQPLTVYFSLSLL
sp|P36544|ACHA7_HUMAN      MRCSPGGVWLALAASLLHVSLQGEFQRKLYKELVKNYNPLERPVANDSQPLTVYFSLSLL
                                  : *  **.::. ********.***:*:************** ******:***:

sp|P22770|ACHA7_CHICK      QIMDVDEKNQVLTTNIWLQMYWTDHYLQWNVSEYPGVKNVRFPDGLIWKPDILLYNSADE
sp|Q05941|ACHA7_RAT        QIMDVDEKNQVLTTNIWLQMSWTDHYLQWNMSEYPGVKNVRFPDGQIWKPDILLYNSADE
sp|P49582|ACHA7_MOUSE      QIMDVDEKNQVLTTNIWLQMSWTDHYLQWNMSEYPGVKNVRFPDGQIWKPDILLYNSADE
sp|P54131|ACHA7_BOVIN      QIMDVDEKNQVLTTNIWLQMTWTDHYLQWNASEYPGVKTVRFPDGQIWKPDILLYNSADE
sp|Q866A2|ACHA7_MACMU      QIMDVDEKNQVLTTNIWLQMSWTDHYLQWNVSEYPGVKTVRFPDGQIWKPDILLYNSADE
sp|P36544|ACHA7_HUMAN      QIMDVDEKNQVLTTNIWLQMSWTDHYLQWNVSEYPGVKTVRFPDGQIWKPDILLYNSADE
                           ******************** ********* *******.****** **************

sp|P22770|ACHA7_CHICK      RFDATFHTNVLVNSSGHCQYLPPGIFKSSCYIDVRWFPFDVQKCNLKFGSWTYGGWSLDL
sp|Q05941|ACHA7_RAT        RFDATFHTNVLVNASGHCQYLPPGIFKSSCYIDVRWFPFDVQQCKLKFGSWSYGGWSLDL
sp|P49582|ACHA7_MOUSE      RFDATFHTNVLVNASGHCQYLPPGIFKSSCYIDVRWFPFDVQQCKLKFGSWSYGGWSLDL
sp|P54131|ACHA7_BOVIN      RFDATFHTNVLVNSSGHCQYLPPGIFKSSCYIDVRWFPFDVQQCKLKFGSWSYGGWSLDL
sp|Q866A2|ACHA7_MACMU      RFDATFHTNVLVNSSGHCQYLPPGIFKSSCYIDVRWFPFDVQHCKLKFGSWSYGGWSLDL
sp|P36544|ACHA7_HUMAN      RFDATFHTNVLVNSSGHCQYLPPGIFKSSCYIDVRWFPFDVQHCKLKFGSWSYGGWSLDL
                           *************:****************************:*:******:********

sp|P22770|ACHA7_CHICK      QMQEADISGYISNGEWDLVGIPGKRTESFYECCKEPYPDITFTVTMRRRTLYYGLNLLIP
sp|Q05941|ACHA7_RAT        QMQEADISSYIPNGEWDLMGIPGKRNEKFYECCKEPYPDVTYTVTMRRRTLYYGLNLLIP
sp|P49582|ACHA7_MOUSE      QMQEADISSYIPNGEWDLMGIPGKRNEKFYECCKEPYPDVTYTVTMRRRTLYYGLNLLIP
sp|P54131|ACHA7_BOVIN      QMQEADISGYIPNGEWDLVGVLGKRSEKFYECCKEPYPDVTFTVSIRRRTLYYGLNLLIP
sp|Q866A2|ACHA7_MACMU      QMQEADISGYIPSGEWDLVGIPGKRSEKFYECCKEPYPDVTFTVTMRRRTLYYGLNLLIP
sp|P36544|ACHA7_HUMAN      QMQEADISGYIPNGEWDLVGIPGKRSERFYECCKEPYPDVTFTVTMRRRTLYYGLNLLIP
                           ********.**..*****:*: ***.* ***********:*:**::**************

sp|P22770|ACHA7_CHICK      CVLISALALLVFLLPADSGEKISLGITVLLSLTVFMLLVAEIMPATSDSVPLIAQYFAST
sp|Q05941|ACHA7_RAT        CVLISALALLVFLLPADSGEKISLGITVLLSLTVFMLLVAEIMPATSDSVPLIAQYFAST
sp|P49582|ACHA7_MOUSE      CVLISALALLVFLLPADSGEKISLGITVLLSLTVFMLLVAEIMPATSDSVPLIAQYFAST
sp|P54131|ACHA7_BOVIN      CVLISALALLVFLLPADSGEKISLGITVLLSLTVFMLLVAEIMPATSDSVPLIAQYFAST
sp|Q866A2|ACHA7_MACMU      CVLISALALLVFLLPADSGEKISLGITVLLSLTVFMLLVAEIMPATSDSVPLIAQYFAST
sp|P36544|ACHA7_HUMAN      CVLISALALLVFLLPADSGEKISLGITVLLSLTVFMLLVAEIMPATSDSVPLIAQYFAST
                           ************************************************************

sp|P22770|ACHA7_CHICK      MIIVGLSVVVTVIVLQYHHHDPDGGKMPKWTRVILLNWCAWFLRMKRPGEDKVRPACQHK
sp|Q05941|ACHA7_RAT        MIIVGLSVVVTVIVLRYHHHDPDGGKMPKWTRIILLNWCAWFLRMKRPGEDKVRPACQHK
sp|P49582|ACHA7_MOUSE      MIIVGLSVVVTVIVLRYHHHDPDGGKMPKWTRIILLNWCAWFLRMKRPGEDKVRPACQHK
sp|P54131|ACHA7_BOVIN      MIIVGLSVVVTVIVLQYHHHDPDGGKMPKWTRVVLLNWCAWFLRMKRPGEDKVRPACQHN
sp|Q866A2|ACHA7_MACMU      MIIVGLSVVVTVIVLQYHHHDPDGGKMPKWTRVILLNWCAWFLRMKRPGEDKVRPACQHK
sp|P36544|ACHA7_HUMAN      MIIVGLSVVVTVIVLQYHHHDPDGGKMPKWTRVILLNWCAWFLRMKRPGEDKVRPACQHK
                           ***************.****************::*************************:

sp|P22770|ACHA7_CHICK      QRRCSLSSMEMNTVSGQQCSNGNMLYIGFRGLDGVHCTPTTDSGVICGRMTCSPTEEENL
sp|Q05941|ACHA7_RAT        PRRCSLASVELSAGAGPPTSNGNLLYIGFRGLEGMHCAPTPDSGVVCGRLACSPTHDEHL
sp|P49582|ACHA7_MOUSE      PRRCSLASVELSAGAGPPTSNGNLLYIGFRGLEGMHCAPTPDSGVVCGRLACSPTHDEHL
sp|P54131|ACHA7_BOVIN      ERRCSLASVEMSAVAGPPATNGNLLYIGFRGLDTMHCAPTPDSGVVCGRVACSPTHDEHL
sp|Q866A2|ACHA7_MACMU      QRRCSLASVEMSAVAPPPASNGNLLYIGFRGLDGMHCAPTPDSGVVCGRMACSPTHDEHL
sp|P36544|ACHA7_HUMAN      QRRCSLASVEMSAVAPPPASNGNLLYIGFRGLDGVHCVPTPDSGVVCGRMACSPTHDEHL
                            *****:*:*:.: :    :***:********: :**.**.****:***::**** :*:*

sp|P22770|ACHA7_CHICK      LHSGHPSEGDPDLAKILEEVRYIANRFRDQDEEEAICNEWKFAASVVDRLCLMAFSVFTI
sp|Q05941|ACHA7_RAT        MHGAHPSDGDPDLAKILEEVRYIANRFRCQDESEVICSEWKFAACVVDRLCLMAFSVFTI
sp|P49582|ACHA7_MOUSE      MHGTHPSDGDPDLAKILEEVRYIANRFRCQDESEVICSEWKFAACVVDRLCLMAFSVFTI
sp|P54131|ACHA7_BOVIN      LHAGQPSEGDPDLAKILEEVRYIAHRFRCQDESEAVCSEWKFAACVVDRLCLMAFSVFTI
sp|Q866A2|ACHA7_MACMU      LHGGQPPEGDPDLAKILEEVRYIANRFRCQDESEAVCSEWKFAACVVDRLCLMAFSVFTI
sp|P36544|ACHA7_HUMAN      LHGGQPPEGDPDLAKILEEVRYIANRFRCQDESEAVCSEWKFAACVVDRLCLMAFSVFTI
                           :*. :*.:****************:*** ***.*.:*.******.***************

sp|P22770|ACHA7_CHICK      ICTIGILMSAPNFVEAVSKDFA
sp|Q05941|ACHA7_RAT        ICTIGILMSAPNFVEAVSKDFA
sp|P49582|ACHA7_MOUSE      ICTIGILMSAPNFVEAVSKDFA
sp|P54131|ACHA7_BOVIN      LCTIGILMSAPNFVEAVSKDFA
sp|Q866A2|ACHA7_MACMU      ICTIGILMSAPNFVEAVSKDFA
sp|P36544|ACHA7_HUMAN      ICTIGILMSAPNFVEAVSKDFA
                           :*********************
