CLUSTAL multiple sequence alignment by MUSCLE (3.8)


sp|P02718|ACHD_TETCF      MGNIHFVYLLISCLYYS---GCSGVNEEERLINDLLIVNKYNKHVRPVKHNNEVVNIALS
sp|P09628|ACHD_XENLA      MAWIWISLLLPILIYFP---GCFSESEEERLLNHIFVERGYRKELRPVEHTGETVNVSLA
sp|P02717|ACHD_CHICK      ---MAVLLALFGALVLS---GGLCVNQEERLIHHLFEERGYNKEVRPVASADEVVDVYLA
sp|P02716|ACHD_MOUSE      MAGPVLTLGLLAALVVCALPGSWGLNEEQRLIQHLFNEKGYDKDLRPVARKEDKVDVALS
sp|P25110|ACHD_RAT        MAGPVPTLGLLAALVVC---GSWGLNEEQRLIQHLFEEKGYNKELRPVARKEDIVDVALS
sp|Q07001|ACHD_HUMAN      MEGPVLTLGLLAALAVC---GSWGLNEEERLIRHLFQEKGYNKELRPVAHKEESVDVALA
sp|P04759|ACHD_BOVIN      MEGSVLTLVLLAALVVC---GSWGLNEEERLIRHLFEEKAYNKELRPAAHK-ESVEISLA
                                   *   :      *    .:*:**:. ::  . * * :**.    : *:: *:

sp|P02718|ACHD_TETCF      LTLSNLISLKETDETLTSNVWMDHAWYDHRLTWNASEYSDISILRLPPELVWIPDIVLQN
sp|P09628|ACHD_XENLA      LTLSNLISLKEADETLTTNVWVELAWYDKRLAWDMETYNNIDILRVPPDMVWQPQLILEN
sp|P02717|ACHD_CHICK      LTLSNLISLKEVDETLTTNVWVEQSWTDYRLQWNTSEFGGVDVLRLLPEMLWLPEIVLEN
sp|P02716|ACHD_MOUSE      LTLSNLISLKEVEETLTTNVWIDHAWVDSRLQWDANDFGNITVLRLPPDMVWLPEIVLEN
sp|P25110|ACHD_RAT        LTLSNLISLKEVEETLTTNVWIDHAWIDSRLQWNANEFGNITVLRLPSDMVWLPEIVLEN
sp|Q07001|ACHD_HUMAN      LTLSNLISLKEVEETLTTNVWIEHGWTDNRLKWNAEEFGNISVLRLPPDMVWLPEIVLEN
sp|P04759|ACHD_BOVIN      LTLSNLISLKEVEETLTTNVWIEQGWTDSRLQWDAEDFGNISVLRLPADMVWLPEIVLEN
                          ***********.:****:***:: .* * ** *: . :..: :**: .:::* *:::*:*

sp|P02718|ACHD_TETCF      NNDGQYHVAYFCNVLVRPNGYVTWLPPAIFRSSCPINVLYFPFDWQNCSLKFTALNYDAN
sp|P09628|ACHD_XENLA      NNNGVFEVAYYSNVLISSDGFMYWLPPAIFQTSCSINVNYFPFDWQNCSLKFSSLTYNAK
sp|P02717|ACHD_CHICK      NNDGLFEVAYYCNVLVYNTGYVYWLPPAIFRSACPINVNFFPFDWQNCTLKFSSLAYNAQ
sp|P02716|ACHD_MOUSE      NNDGSFQISYACNVLVYDSGYVTWLPPAIFRSSCPISVTYFPFDWQNCSLKFSSLKYTAK
sp|P25110|ACHD_RAT        NNDGSFQISYACNVLVSDSGHVTWLPPAIFRSSCPISVTYFPFDWQNCSLKFSSLKYTAK
sp|Q07001|ACHD_HUMAN      NNDGSFQISYSCNVLVYHYGFVYWLPPAIFRSSCPISVTYFPFDWQNCSLKFSSLKYTAK
sp|P04759|ACHD_BOVIN      NNDGSFQISYSCNVLIYPSGSVYWLPPAIFRSSCPISVTYFPFDWQNCSLKFSSLKYTTK
                          **:* : ::* .***:   * : *******.::*.*.* :********:***::* * ::

sp|P02718|ACHD_TETCF      EITMDLMTDT--IDGKDYPIEWIIIDPEAFTENGEWEIIHKPAKKNIYPDKFPNGTNYQD
sp|P09628|ACHD_XENLA      EINLQLRQDLDEASQRYYPVEWIIIDPEGFTENGEWEIVHIPAKKNIDRSLSPESTKYQD
sp|P02717|ACHD_CHICK      EINMHLKEESDPETEKNYRVEWIIIDPEGFTENGEWEIIHRPARKNIHPSYPTESSEHQD
sp|P02716|ACHD_MOUSE      EITLSLKQEE--ENNRSYPIEWIIIDPEGFTENGEWEIVHRAAKLNVDPSVPMDSTNHQD
sp|P25110|ACHD_RAT        EIRLSLKQEE--EDNRSYPIEWIIIDPEGFTENGEWEIVHRAAKVNVDPSVPMDSTNHQD
sp|Q07001|ACHD_HUMAN      EITLSLKQDA--KENRTYPVEWIIIDPEGFTENGEWEIVHRPARVNVDPRAPLDSPSRQD
sp|P04759|ACHD_BOVIN      EITLSLKQAE--EDGRSYPVEWIIIDPEGFTENGEWEIVHRPARVNVDPSVPLDSPNRQD
                          ** : *         . * :********.*********:* .*. *:      :... **

sp|P02718|ACHD_TETCF      VTFYLIIRRKPLFYVINFITPCVLISFLASLAFYLPAESGEKMSTAISVLLAQAVFLLLT
sp|P09628|ACHD_XENLA      ITFYLIIERKPLFYIINILAPCVLIALMANLVFYLPADSGEKMTLAISVLLAQSVFLLLI
sp|P02717|ACHD_CHICK      ITFYLIIKRKPLFYVINIVTPCVLIAFMAILVFYLPADSGEKMTLVISVLLAQSVFLLLV
sp|P02716|ACHD_MOUSE      VTFYLIIRRKPLFYIINILVPCVLISFMINLVFYLPGDCGEKTSVAISVLLAQSVFLLLI
sp|P25110|ACHD_RAT        VTFYLIIRRKPLFYIINILVPCVLISFMINLVFYLPGDCGEKTSVAISVLLAQSVFLLLI
sp|Q07001|ACHD_HUMAN      ITFYLIIRRKPLFYIINILVPCVLISFMVNLVFYLPADSGEKTSVAISVLLAQSVFLLLI
sp|P04759|ACHD_BOVIN      VTFYLIIRRKPLFYVINILVPCVLISFMINLVFYLPADCGEKTSMAISVLLAQSVFLLLI
                          :****** ******:**::.*****:::  *.****.:.*** : .*******:***** 

sp|P02718|ACHD_TETCF      SQRLPETALAVPLIGKYLMFIMSLVTGVIVNCGIVLNFHFRTPSTHVLSTRVKQIFLEKL
sp|P09628|ACHD_XENLA      SQRLPETSFAIPLISKYLMFIMVLVTIVVVSCVIVLNLHFRTPSTHAISERMKEIFLNKL
sp|P02717|ACHD_CHICK      SQRLPATSHAIPLIGKYLLFIMLLVTAVVVICVVVLNFHFRTPSTHVMSDWVRGVFLEIL
sp|P02716|ACHD_MOUSE      SKRLPATSMAIPLVGKFLLFGMVLVTMVVVICVIVLNIHFRTPSTHVLSEGVKKFFLETL
sp|P25110|ACHD_RAT        SKRLPATSMAIPLVGKFLLFGMVLVTMVVVICVIVLNIHFRTPSTHVLSEGVKKFFLETL
sp|Q07001|ACHD_HUMAN      SKRLPATSMAIPLIGKFLLFGMVLVTMVVVICVIVLNIHFRTPSTHVLSEGVKKLFLETL
sp|P04759|ACHD_BOVIN      SKRLPATSMAIPLIGKFLLFGMVLVTMVVVICVIVLNIHFRTPSTHVLSEPVKKLFLETL
                          *:*** *: *:**:.*:*:* * *** *:* * :***:********.:*  :. .**: *

sp|P02718|ACHD_TETCF      PRILHMSRADESEQPDWQNDLKLRRSSSVGYISKAQEYFNIKSRSELMFEKQSERHGLVP
sp|P09628|ACHD_XENLA      PRILHMSQPAEPEPEPWSGVL-LRRSSSVGYIVKAEEYYSVKSRSELMFEKQSERHGLTS
sp|P02717|ACHD_CHICK      PRLLHMSHPAE-SPAG--APC-IRRCSSAGYIAKAEEYYSVKSRSELMFEKQSERHGLAS
sp|P02716|ACHD_MOUSE      PKLLHMSRPAEEDPGP--RAL-IRRSSSLGYICKAEEYFSLKSRSDLMFEKQSERHGLAR
sp|P25110|ACHD_RAT        PKLLHMSRPEEEDPGP--RAL-IRRTSSLGYISKAEEYFSLKSRSDLMFEKQSERHGLAR
sp|Q07001|ACHD_HUMAN      PELLHMSRPAEDGPSP--GAL-VRRSSSLGYISKAEEYFLLKSRSDLMFEKQSERHGLAR
sp|P04759|ACHD_BOVIN      PEILHMSRPAEDGPSP--GTL-IRRSSSLGYISKAEEYFSLKSRSDLMFEKQSERHGLAR
                          * :****.. *           :** ** *** **:**: :****:************. 

sp|P02718|ACHD_TETCF      RVTPRIGFGNNNENIAASDQLHDEIKSGIDSTNYIVKQIKEKNAYDEEVGNWNLVGQTID
sp|P09628|ACHD_XENLA      RATPARVNPLNANN--SQDQLYGEIKPAIDGANFIVKHIRDKNDYNEEKDNWYRIARTVD
sp|P02717|ACHD_CHICK      RVTPARFAPAAT----SEEQLYDHLKPTLDEANFIVKHMREKNSYNEEKDNWNRVARTLD
sp|P02716|ACHD_MOUSE      RLTTARRPPASSEQ--VQQELFNEMKPAVDGANFIVNHMRDQNSYNEEKDNWNQVARTVD
sp|P25110|ACHD_RAT        RLTTARKPPASSEQ--VQQELFNEMKPAVDGANFIVNHMRDQNSYNEEKDNWNQVARTVD
sp|Q07001|ACHD_HUMAN      RLTTARRPPASSEQ--AQQELFNELKPAVDGANFIVNHMRDQNNYNEEKDSWNRVARTVD
sp|P04759|ACHD_BOVIN      RLTTARRPPAGSEQ--AQQELFSELKPAVDGANFIVNHMKDQNNYNEEKDCWNRVARTVD
                          * *.             .::*.. :*. :* :*:**:::.::* *:** . *  :..*:*

sp|P02718|ACHD_TETCF      RLSMFIITPVMVLGTIFIFVMGNFNHPPAKPFEGDPFDYSSDHPRCA
sp|P09628|ACHD_XENLA      RLCLFLVTPVMIIGTLWIFLGGAYNLPPSLPFPGDPFIYTKEHRRLI
sp|P02717|ACHD_CHICK      RLCLFLITPMLVVGTLWIFLMGIYNHPPPLPFSGDPFDYREENKRYI
sp|P02716|ACHD_MOUSE      RLCLFVVTPVMVVGTAWIFLQGVYNQPPLQPFPGDPFSYSEQDKRFI
sp|P25110|ACHD_RAT        RLCLFVVTPVMVVGTAWIFLQGVYNQPPPQPFPGDPFSYDEQDRRFI
sp|Q07001|ACHD_HUMAN      RLCLFVVTPVMVVGTAWIFLQGVYNQPPPQPFPGDPYSYNVQDKRFI
sp|P04759|ACHD_BOVIN      RLCLFVVTPIMVVGTAWIFLQGAYNQPPPQPFPGDPFSYLEKDKRFI
                          **.:*::**::::** :**: * :* **  ** ***: *  .  *  
