CLUSTAL multiple sequence alignment by MUSCLE (3.8)


sp|P49580|ACHE_XENLA      MESGVRILSLLILLHNSLASESEESRLIKHLFTSYDQKARPSKGLDDVVPVTLKLTLTNL
sp|P20782|ACHE_MOUSE      MAGALLGALLLLTLFGRSQGKNEELSLYHHLFDNYDPECRPVRRPEDTVTITLKVTLTNL
sp|P09660|ACHE_RAT        MTMALLGTLLLLALFGRSQGKNEELSLYHHLFDNYDPECRPVRRPEDTVTITLKVTLTNL
sp|P02715|ACHE_BOVIN      MAGALLCALLLLQLLGRGEGKNEELRLYHYLFDTYDPGRRPVQEPEDTVTISLKVTLTNL
sp|Q04844|ACHE_HUMAN      MARAPLGVLLLLGLLGRGVGKNEELRLYHHLFNNYDPGSRPVREPEDTVTISLKVTLTNL
                          *  .     **: * .   .:.**  * ::** .**   ** .  :*.*.::**:*****

sp|P49580|ACHE_XENLA      IDLNEKEETLTTNVWVQIAWNDDRLVWNVTDYGGIGFVPVPHDIMWLPDIVLENNIDGNF
sp|P20782|ACHE_MOUSE      ISLNEKEETLTTSVWIGIDWHDYRLNYSKDDFAGVGILRVPSEHVWLPEIVLENNIDGQF
sp|P09660|ACHE_RAT        ISLNEKEETLTTSVWIGIEWQDYRLNFSKDDFAGVEILRVPSEHVWLPEIVLENNIDGQF
sp|P02715|ACHE_BOVIN      ISLNEKEETLTTSVWIGIDWQDYRLNYSKGDFGGVETLRVPSELVWLPEIVLENNIDGQF
sp|Q04844|ACHE_HUMAN      ISLNEKEETLTTSVWIGIDWQDYRLNYSKDDFGGIETLRVPSELVWLPEIVLENNIDGQF
                          *.**********.**: * *:* ** :.  *:.*:  : ** : :***:*********:*

sp|P49580|ACHE_XENLA      EVAYYANVLVYNTGYIYWLPPAIFRSTCNIEITYFPFDWQNCSLVFRSKTYSANEIDLQL
sp|P20782|ACHE_MOUSE      GVAYDSNVLVYEGGYVSWLPPAIYRSTCAVEVTYFPFDWQNCSLIFRSQTYNAEEVEFIF
sp|P09660|ACHE_RAT        GVAYDCNVLVYEGGSVSWLPPAIYRSTCAVEVTYFPFDWQNCSLIFRSQTYNAEEVELIF
sp|P02715|ACHE_BOVIN      GVAYEANVLVSEGGYLSWLPPAIYRSTCAVEVTYFPFDWQNCSLVFRSQTYNAEEVEFVF
sp|Q04844|ACHE_HUMAN      GVAYDANVLVYEGGSVTWLPPAIYRSVCAVEVTYFPFDWQNCSLIFRSQTYNAEEVEFTF
                           *** .**** : * : ******:**.* :*:************:***:**.*:*::: :

sp|P49580|ACHE_XENLA      VTDDETGLPFDQVDIDREAFTENGEWAIMHRPARKILNPKYSKEDLRYQEIVFNLIIQRK
sp|P20782|ACHE_MOUSE      AVDDD-GNTINKIDIDTAAFTENGEWAIDYCPGMIRRYEGGSTEGPGETDVIYTLIIRRK
sp|P09660|ACHE_RAT        AVDDD-GNAINKIDIDTAAFTENGEWAIDYCPGMIRHYEGGSTEDPGETDVIYTLIIRRK
sp|P02715|ACHE_BOVIN      AVDDE-GKTISKIDIDTEAYTENGEWAIDFCPGVIRRHDGDSAGGPGETDVIYSLIIRRK
sp|Q04844|ACHE_HUMAN      AVDND-GKTINKIDIDTEAYTENGEWAIDFCPGVIRRHHGGATDGPGETDVIYSLIIRRK
                          ..*:: * .:.::***  *:******** . *.        :  .    ::::.***.**

sp|P49580|ACHE_XENLA      PLFYIINIIVPCVLISFLVVLVYFLPAKAGGQKCTVSISVLLAQTVFLFLIAQMVPETSL
sp|P20782|ACHE_MOUSE      PLFYVINIIVPCVLISGLVLLAYFLPAQAGGQKCTVSINVLLAQTVFLFLIAQKIPETSL
sp|P09660|ACHE_RAT        PLFYVINIIVPCVLISGLVLLAYFLPAQAGGQKCTVSINVLLAQTVFLFLIAQKIPETSL
sp|P02715|ACHE_BOVIN      PLFYVINIIVPCVLISGLVLLAYFLPAQAGGQKCTVSINVLLAQTVFLFLIAQKTPETSL
sp|Q04844|ACHE_HUMAN      PLFYVINIIVPCVLISGLVLLAYFLPAQAGGQKCTVSINVLLAQTVFLFLIAQKIPETSL
                          ****:*********** **:*.*****:**********.**************  *****

sp|P49580|ACHE_XENLA      SVPLIGKYLMFVMFVSTLIVLSCVIVLNVSLRSPSTHNLSTKVKHMLLEVLPQFLHLRVE
sp|P20782|ACHE_MOUSE      SVPLLGRYLIFVMVVATLIVMNCVIVLNVSLRTPTTHATSPRLRQILLELLPRLLGSSPP
sp|P09660|ACHE_RAT        SVPLLGRYLIFVMVVATLIVMNCVIVLNVSLRTPTTHATSPRLRQILLELLPRLLGLSPP
sp|P02715|ACHE_BOVIN      SVPLLGRYLIFVMVVATLIVMNCVIVLNVSLRTPTTHAMSPRLRYVLLELLPQLLGSGAP
sp|Q04844|ACHE_HUMAN      SVPLLGRFLIFVMVVATLIVMNCVIVLNVSQRTPTTHAMSPRLRHVLLELLPRLLGSPPP
                          ****:*.:*:***.*:****:.******** *:*:**  *..:. :***:**.:*     

sp|P49580|ACHE_XENLA      PCDEGEETPRERRRSSLGIMLKAEEYVLKKPRSELMFERQRERHGMRREPDGYRADGFDV
sp|P20782|ACHE_MOUSE      PEDPRTASP-ARRASSVGILLRAEELILKKPRSELVFEGQRHRHGTW-------------
sp|P09660|ACHE_RAT        PEDPGAASP-ARRASSVGILLRAEELILKKPRSELVFEGQRHRHGTW-------------
sp|P02715|ACHE_BOVIN      PEIPRAASP-PRRASSLGLLLRAEELILKKPRSELVFEQQRHRHGTW-------------
sp|Q04844|ACHE_HUMAN      PEAPRAASP-PRRASSVGLLLRAEELILKKPRSELVFEGQRHRQGTW-------------
                          *      :*  ** **:*::*.*** :********:** ** *:* .             

sp|P49580|ACHE_XENLA      GVT-TTLYRNLAQCAPEIKDCVDACNFITQNTKEQNRTGSEMENWILIGKVLDVLCFWVA
sp|P20782|ACHE_MOUSE      --T-AALCQNLGAAAPEIRCCVDAVNFVAESTRDQEATGEELSDWVRMGKALDNVCFWAA
sp|P09660|ACHE_RAT        --TAAALCQNLGAAAPEVRCCVDAVNFVAESTRDQEATGEELSDWVRMGKALDNVCFWAA
sp|P02715|ACHE_BOVIN      --T-ATLCQNLGAAAPEIRCCVDAVNFVASSTRDQEATGEEVSDWVRMGKALDSICFWAA
sp|Q04844|ACHE_HUMAN      --T-AAFCQSLGAAAPEVRCCVDAVNFVAESTRDQEATGEEVSDWVRMGNALDNICFWAA
                            * ::: ..*. .***:. **** **::..*.:*: **.*:.:*: :*:.** :***.*

sp|P49580|ACHE_XENLA      LPLFVLGTLAIFLMGHFNTAPEHPF------
sp|P20782|ACHE_MOUSE      LVLFSVGSTLIFLGGYFNQVPDLPYPPCIQP
sp|P09660|ACHE_RAT        LVLFSVGSTLIFLGGYFNQVPDLPYPPCIQP
sp|P02715|ACHE_BOVIN      LVLFLVGSSLIFLGAYFNRVPQLPYPPCM--
sp|Q04844|ACHE_HUMAN      LVLFSVGSSLIFLGAYFNRVPDLPYAPCIQP
                          * ** :*:  *** .:** .*: *:      
