CLUSTAL multiple sequence alignment by MUSCLE (3.8)


sp|P02714|ACHG_TETCF      -----MVLTLLLIICLALEVRSENEEGRLIEKLLGDYDKRIIPAKTLDHIIDVTLKLTLT
sp|P04760|ACHG_MOUSE      MQGGQRPHLLLLLLAVCLGAQSRNQEERLLADLMRNYDPHLRPAERDSDVVNVSLKLTLT
sp|P18916|ACHG_RAT        MHGGQGPQLLLLLLATCLGAQSRNQEERLLADLMRNYDPHLRPAERDSDVVNVSLKLTLT
sp|P07510|ACHG_HUMAN      MHGGQGPLLLLLLLAVCLGAQGRNQEERLLADLMQNYDPNLRPAERDSDVVNVSLKLTLT
sp|P13536|ACHG_BOVIN      MCGGQRPLFLLPLLAVCLGAKGRNQEERLLGDLMQGYNPHLRPAEHDSDVVNVSLKLTLT
sp|P02713|ACHG_CHICK      MRCSDLLLLFLLALCVLPGISCRNQEEKLLQDLMTNYNRHLRPALRGDQVIDVTLKLTLT
sp|P05376|ACHG_XENLA      ----MDTVLLLVSLCIS-AAFCNNEEERLLNDLMKNYNKNLRPVEKDGDIISVSIKLTLT
                                   :*  :.        *:* .*: .*: .*: .: *.   . ::.*::*****

sp|P02714|ACHG_TETCF      NLISLNEKEEALTTNVWIEIQWNDYRLSWNTSEYEGIDLVRIPSELLWLPDVVLENNVDG
sp|P04760|ACHG_MOUSE      NLISLNEREEALTTNVWIEMQWCDYRLRWDPKDYEGLWILRVPSTMVWRPDIVLENNVDG
sp|P18916|ACHG_RAT        NLISLNEREEALTTNVWIEMQWCDYRLRWDPKDYEGLWILRVPSTMVWQPDIVLGNNVDG
sp|P07510|ACHG_HUMAN      NLISLNEREEALTTNVWIEMQWCDYRLRWDPRDYEGLWVLRVPSTMVWRPDIVLENNVDG
sp|P13536|ACHG_BOVIN      NLISLNEREEALTTNVWIEMQWCDYRLRWDPRDYGGLWVLRVPSTMVWRPDIVLENNVDG
sp|P02713|ACHG_CHICK      NLISLNEREETLTTNVWIEMQWSDYRLRWDPDKYDDIQQLRVPSAMVWLPDIVLENNIDG
sp|P05376|ACHG_XENLA      NLISLNEKEEALTTNVWVEMQWKDYRLSWDPNDYHGISMMRIPSTSVWLPDVGLENNVDG
                          *******.**:******:*:** **** *:. .* .:  :*:**  :* **: * **:**

sp|P02714|ACHG_TETCF      QFEVAYYANVLVYNDGSMYWLPPAIYRSTCPIAVTYFPFDWQNCSLVFRSQTYNAHEVNL
sp|P04760|ACHG_MOUSE      VFEVALYCNVLVSPDGCIYWLPPAIFRSSCSISVTYFPFDWQNCSLIFQSQTYSTSEINL
sp|P18916|ACHG_RAT        VFEVALYCNVLVSPDGCIYWLPPAIFRSSCSISVTYFPFDWQNCSLVFQSQTYSTSEINL
sp|P07510|ACHG_HUMAN      VFEVALYCNVLVSPDGCIYWLPPAIFRSACSISVTYFPFDWQNCSLIFQSQTYSTNEIDL
sp|P13536|ACHG_BOVIN      VFEVALYCNVLVSPDGCVYWLPPAIFRSSCPVSVTFFPFDWQNCSLIFQSQTYSTNEINL
sp|P02713|ACHG_CHICK      TFEITLYTNVLVYPDGSIYWLPPAIYRSSCSIHVTYFPFDWQNCTMVFQSQTYSANEINL
sp|P05376|ACHG_XENLA      TFDIALYTNTLVSSDGSMYWLPPAIYRSSCPVVVTYFPFDWQNCSIVFQSQTYSANEIEL
                           *::: * *.**  **.:*******:**:*.: **:********:::*.****.: *::*

sp|P02714|ACHG_TETCF      QLSAEEGEAVEWIHIDPEDFTENGEWTIRHRPAKKNYNW-QLTKDDTDFQEIIFFLIIQR
sp|P04760|ACHG_MOUSE      QLSQEDGQAIEWIFIDPEAFTENGEWAIRHRPAKMLLDS-VAPAEEAGHQKVVFYLLIQR
sp|P18916|ACHG_RAT        QLSQEDGQAIEWIFIDPEAFTENGEWAIRHRPAKMLLDP-VTPAEEAGHQKVVFYLLIQR
sp|P07510|ACHG_HUMAN      QLSQEDGQTIEWIFIDPEAFTENGEWAIQHRPAKMLLDP-AAPAQEAGHQKVVFYLLIQR
sp|P13536|ACHG_BOVIN      QLSQEDGQTIEWIFIDPEAFTENGEWAIRHRPAKMLLDE-AAPAEEAGHQKVVFYLLIQR
sp|P02713|ACHG_CHICK      LLTVEEGQTIEWIFIDPEAFTENGEWAIKHRPARKIINSGRFTPDDIQYQQVIFYLIIQR
sp|P05376|ACHG_XENLA      LLTVDE-QTIEWIEIDPEAFTENGEWAIKHMPAKRIINH-RLPRDDVNYQQIVFYLIIQR
                           *: :: :::*** **** *******:*.* **.   :    . ::  .*:::*:*:***

sp|P02714|ACHG_TETCF      KPLFYIINIIAPCVLISSLVVLVYFLPAQAGGQKCTLSISVLLAQTIFLFLIAQKVPETS
sp|P04760|ACHG_MOUSE      KPLFYVINIIAPCVLISSVAILIYFLPAKAGGQKCTVATNVLLAQTVFLFLVAKKVPETS
sp|P18916|ACHG_RAT        KPLFYVINIIVPCVLISSVAILIYFLPAKAGGQKCTVATNVLLAQTVFLFLVAKKVPETS
sp|P07510|ACHG_HUMAN      KPLFYVINIIAPCVLISSVAILIHFLPAKAGGQKCTVAINVLLAQTVFLFLVAKKVPETS
sp|P13536|ACHG_BOVIN      KPLFYVINIIAPCVLISSVAILIYFLPAKAGGQKCTVAINVLLAQTVFLFLVAKKVPETS
sp|P02713|ACHG_CHICK      KPLFYIINIIVPCVLISSMAVLVYFLPAKAGGQKCTVSINVLLAQTVFLFLIAQKVPETS
sp|P05376|ACHG_XENLA      KPLFYIINIIVPCVLISFVSILVYFLPAKAGGQKCTVSINILLAQTVFLFLVAQKIPETS
                          *****:****.****** : :*::****:*******:: .:*****:****:*:*:****

sp|P02714|ACHG_TETCF      LNVPLIGKYLIFVMFVSMLIVMNCVIVLNVSLRTPNTHSLSEKIKHLFLGFLPKYLGMQL
sp|P04760|ACHG_MOUSE      QAVPLISKYLTFLMVVTILIVVNSVVVLNVSLRSPHTHSMARGVRKLFLRLLPQLLRMHV
sp|P18916|ACHG_RAT        QAVPLISKYLTFLMVVTILIVVNSVVVLNVSLRSPHTHSMARGVRKVFLRLLPQLLRMHV
sp|P07510|ACHG_HUMAN      QAVPLISKYLTFLLVVTILIVVNAVVVLNVSLRSPHTHSMARGVRKVFLRLLPQLLRMHV
sp|P13536|ACHG_BOVIN      QAVPLISKYLTFLLVVTILIVVNAVVVLNVSLRSPHTHSMARGVRKVFLRLLPQLLRMHV
sp|P02713|ACHG_CHICK      QAVPLIGKYLTFLMVVTVVIVVNAVIVLNVSLRTPNTHSMSQRVRQVWLHLLPRYLGMHM
sp|P05376|ACHG_XENLA      TSVPLIVKYLTFLMVVTITIVANAVIVLNISLRTPNTHSMSSTVRELCLRTVPRLLRMHL
                            **** *** *::.*:: ** *.*:***:***:*:***::  :. : *  :*. * *::

sp|P02714|ACHG_TETCF      EPSEETP-EKPQPRRRS--SFGI-MIKAEEYILKKPRSELMFEEQKDRHGLKR--VNKMT
sp|P04760|ACHG_MOUSE      RPLAPAAVQDARFRLQNGSSSGWPIMAREEGDLCLPRSELLF-RQRQRNGLVQAVLEKLE
sp|P18916|ACHG_RAT        HPRAPAAVQDARLRLQNGSSSGWPIMTREEGDLCLPRSELLF-RQRQRNGLVQAVLEKLE
sp|P07510|ACHG_HUMAN      RPLAPAAVQDTQSRLQNG-SSGWSITTGEEVALCLPRSELLF-QQWQRQGLVAAALEKLE
sp|P13536|ACHG_BOVIN      RPLAPVAVQDAHPRLQNGSSSGWPITAGEEVALCLPRSELLF-RQRQRNGLVRAALEKLE
sp|P02713|ACHG_CHICK      PEEAPGPPQAT--RRRS--SLGL-MVKADEYMLWKARTELLFEKQKERDGLMKTVLEKIG
sp|P05376|ACHG_XENLA      RPTDAAPPLAPLMRRSS--SLGL-MMKADEYMLRKPRSQLMFEKQKERDGLMKVVLDKIG
                                .   .  *  .  * *  :   :*  *  .*::*:*  *.:* **    ::*: 

sp|P02714|ACHG_TETCF      SDIDIGTTVDLYKDLANFAPEIKSCVEACNFIAKSTKEQNDSGSENENWVLIGKVIDKAC
sp|P04760|ACHG_MOUSE      NGPEVRQSQEFCGSLKQASPAIQACVDACNLMARARRQQSHFDSGNEEWLLVGRVLDRVC
sp|P18916|ACHG_RAT        NGPEMRQSQEFCGSLKQASPAIQACVDACNLMARARHQQSHFDSGNEEWLLVGRVLDRVC
sp|P07510|ACHG_HUMAN      KGPELGLSQ-FCGSLKQAAPAIQACVEACNLIACARHQQSHFDNGNEEWFLVGRVLDRVC
sp|P13536|ACHG_BOVIN      KGPESGQSPEWCGSLKQAAPAIQACVEACNLIARARHQQTHFDSGNKEWFLVGRVLDRVC
sp|P02713|ACHG_CHICK      RGLESNCAQDFCQSLEEASPEIRACVEACNHIANATREQNDFSSENEEWILVGRVIDRVC
sp|P05376|ACHG_XENLA      RGMENNTSDDLVHSLNHAAPEIRTCVEACCHIASATREKNDFKSENEEWILMGRVIDRVC
                           . :   :     .*   :* *.:**:**  :* : .::.   . *::*.*:*.*:*..*

sp|P02714|ACHG_TETCF      FWIALLLFSIGTLAIFLTGHFNQVPEFPFPGDPRKYVP---
sp|P04760|ACHG_MOUSE      FLAMLSLFICGTAGIFLMAHYNQVPDLPFPGDPRPYLPLPD
sp|P18916|ACHG_RAT        FLAMLSLFICGTAGIFLMAHYNQVPDLPFPGDPRPYLPLPD
sp|P07510|ACHG_HUMAN      FLAMLSLFICGTAGIFLMAHYNRVPALPFPGDPRPYLPSPD
sp|P13536|ACHG_BOVIN      FLAMLSLFVCGTAGIFLMAHYNRVPALPFPGDPRSYLPSSD
sp|P02713|ACHG_CHICK      FFIMASLFVCGTIGIFLMAHFNQAPALPFPGDPKTYLPP--
sp|P05376|ACHG_XENLA      FLVMCFVFFLGTIGTFLAGHFNQAPAHPFPGDSKLYQPST-
                          *     :*  ** . ** .*:*..*  *****.. * *   
